DROP DATABASE IF EXISTS STUFFER_DB;

CREATE DATABASE STUFFER_DB;

USE STUFFER_DB;

DROP TABLE IF EXISTS IMAGES;
CREATE TABLE IMAGES (
  ID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(150) NOT NULL,
  PATH VARCHAR(1000),
  ORIGINALNAME VARCHAR(150),
  MIMETYPE VARCHAR(150),
  DESTINATION VARCHAR(255),
  SIZE INT,
  CREATEDAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS (
  ID INT NOT NULL AUTO_INCREMENT,
  FIRST_NAME VARCHAR(100) NOT NULL,
  LAST_NAME  VARCHAR(100) NOT NULL,
  EMAIL      VARCHAR(100) NOT NULL,
  PASSWORD VARCHAR(100),
  POSTAL   VARCHAR(5),
  ADDRESS    VARCHAR(255),
  CREATEDAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS CATEGORIES;
CREATE TABLE CATEGORIES (
  ID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(100) NOT NULL,
  CREATEDAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS ITEMS;
CREATE TABLE ITEMS (
  ID INT NOT NULL AUTO_INCREMENT,
  ITEM_NAME VARCHAR(150) NOT NULL,
  DESCRIPTION VARCHAR(1000),
  CATEGORY_ID INT NOT NULL,
  OWNER_ID INT NOT NULL,
  BORROWER_ID INT,
  IMAGE_ID INT,
  PENDING BOOLEAN DEFAULT FALSE,
  AVAILABLE_DATE DATE,
  AVAILABLE_PERIOD INT,
  BORROWED_DATE DATE,
  BORROWED_PERIOD DATE,
  PENALTY DECIMAL(9,2),
  SERIAL_NUMBER VARCHAR(100),
  COST DECIMAL(9,2),
  CREATEDAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID)
);

ALTER TABLE ITEMS
ADD FOREIGN KEY ITEMS_FK1(CATEGORY_ID)
REFERENCES CATEGORIES(ID);
ALTER TABLE ITEMS
ADD FOREIGN KEY ITEMS_FK2(OWNER_ID)
  REFERENCES USERS(ID);
ALTER TABLE ITEMS
ADD FOREIGN KEY ITEMS_FK3(BORROWER_ID)
  REFERENCES USERS(ID);
ALTER TABLE ITEMS
ADD FOREIGN KEY ITEMS_FK4(IMAGE_ID)
  REFERENCES IMAGES(ID);